server:
  port: 8001

spring:
  application:
    name: fullstack-quiz

app:
  version: 0.0.1-SNAPSHOT
  name: FullStack Quiz Application

logging:
  level:
    com.fullstackquiz: INFO
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
